// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5ckZoK49YqVaCRiUOuJkhh3FKcIXi06c',
    appId: '1:931856781528:android:64395b300ef3fc4c8c07ad',
    messagingSenderId: '931856781528',
    projectId: 'epic-tracker-5b28b',
    storageBucket: 'epic-tracker-5b28b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq--eBbWsVovV4s4402FK0Fb4MaW4ASqU',
    appId: '1:931856781528:ios:07eff848616f65948c07ad',
    messagingSenderId: '931856781528',
    projectId: 'epic-tracker-5b28b',
    storageBucket: 'epic-tracker-5b28b.firebasestorage.app',
    iosBundleId: 'com.johnmurindwa.epictracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq--eBbWsVovV4s4402FK0Fb4MaW4ASqU',
    appId: '1:931856781528:ios:7a69df8e23a013498c07ad',
    messagingSenderId: '931856781528',
    projectId: 'epic-tracker-5b28b',
    storageBucket: 'epic-tracker-5b28b.firebasestorage.app',
    iosBundleId: 'com.example.epicTracker',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp2m6q1FnIHEjWt8E3lVRbsVIah5bdLOE',
    appId: '1:931856781528:web:a1acb8da530d866a8c07ad',
    messagingSenderId: '931856781528',
    projectId: 'epic-tracker-5b28b',
    authDomain: 'epic-tracker-5b28b.firebaseapp.com',
    storageBucket: 'epic-tracker-5b28b.firebasestorage.app',
    measurementId: 'G-4KF7SXNL6D',
  );
}
